hopperpw/main/urls.py
# coding=utf-8
from api.views import (
    MyIpView, DetectIpView, NicUpdateView, AuthorizedNicUpdateView)
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from main.views import (
    HomeView, OverviewView, HostView, DeleteHostView, AboutView, HelpView,
    GenerateSecretView, DomainOverwievView, DeleteDomainView, ThankYouView,
    RegistrationSuccessView
)
from stats.views import StatsView


urlpatterns = patterns(
    '',
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^about/$', AboutView.as_view(), name="about"),
    url(r'^thank_you/$', ThankYouView.as_view(), name="thank_you"),
    url(r'^welcome/$', RegistrationSuccessView.as_view(), name="welcome"),
    url(r'^legal/$',
        TemplateView.as_view(template_name='main/legal.html'), name="legal"),
    url(r'^help/$', HelpView.as_view(), name="help"),
    url(r'^stats/$', StatsView.as_view(), name="stats"),
    url(r'^overview/$', OverviewView.as_view(), name='overview'),
    url(r'^host/(?P<pk>\d+)/$', HostView.as_view(), name='host_view'),
    url(r'^generate_secret/(?P<pk>\d+)/$',
        GenerateSecretView.as_view(), name='generate_secret_view'),
    url(r'^host/(?P<pk>\d+)/delete/$',
        DeleteHostView.as_view(), name='delete_host'),
    url(r'^domain_overview/$',
        DomainOverwievView.as_view(), name='domain_overview'),
    url(r'^domain/(?P<pk>\d+)/delete/$',
        DeleteDomainView.as_view(), name='delete_domain'),
    url(r'^myip$', MyIpView),
    url(r'^detectip/$', DetectIpView),
    url(r'^detectip/(?P<secret>\w+)/$', DetectIpView),
    url(r'^nic/update$', NicUpdateView),
    url(r'^nic/update_authorized$',
        AuthorizedNicUpdateView, name='nic_update_authorized'),
)

hopperpw/main/models.py
# coding=utf-8
import base64
import binascii
from datetime import datetime
import dns.resolver
import re

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.signals import post_delete

from main import dnstools


class BaseModel(models.Model):
    last_update = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class BaseModelCreatedBy(BaseModel):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    class Meta:
        abstract = True


class BaseModelRequiredCreatedBy(BaseModel):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        abstract = True


class BlacklistedDomain(BaseModelCreatedBy):
    domain = models.CharField(
        max_length=256,
        unique=True,
        help_text='Blacklisted domain. Evaluated as regex (search).')

    def __unicode__(self):
        return u"%s" % (self.domain, )


def domain_blacklist_validator(value):
    for bd in BlacklistedDomain.objects.all():
        if re.search(bd.domain, value):
            raise ValidationError(u'This domain is not allowed')


def ns_update_key_validator(value):
    try:
        base64.decodestring(value)
    except binascii.Error as e:
        raise ValidationError(u'Invalid update key: Must be base64 (%s)' % e)


UPDATE_ALGORITHMS = (
    ('HMAC_SHA512', 'HMAC_SHA512'),
    ('HMAC_MD5', 'HMAC_MD5'),
)


class Domain(BaseModelCreatedBy):
    domain = models.CharField(max_length=256, unique=True)
    nameserver_ip = models.IPAddressField(
        max_length=256)
    nameserver_update_key = models.CharField(max_length=256, validators=[
        ns_update_key_validator])
    nameserver_update_algorithm = models.CharField(
        max_length=256, choices=UPDATE_ALGORITHMS)
    available_for_everyone = models.BooleanField(default=False)

    def __unicode__(self):
        return u"%s" % (self.domain, )


class Host(BaseModelRequiredCreatedBy):
    subdomain = models.CharField(max_length=256, validators=[
        RegexValidator(
            regex=r'^(([a-z0-9][a-z0-9\-]*[a-z0-9])|[a-z0-9])$',
            message='Invalid subdomain: only "a-z", "0-9" and "-" is allowed'
        ),
        domain_blacklist_validator])
    domain = models.ForeignKey(Domain)
    update_secret = models.CharField(max_length=256)
    comment = models.CharField(
        max_length=256, default='', blank=True, null=True)

    last_api_update = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        return u"%s.%s - %s" % (
            self.subdomain, self.domain.domain, self.comment)

    class Meta:
        unique_together = (('subdomain', 'domain'),)

    def get_fqdn(self):
        return '%s.%s' % (self.subdomain, self.domain.domain)

    @classmethod
    def filter_by_fqdn(cls, fqdn, **kwargs):
        # Assuming subdomain has no dots (.) the fqdn is split at the first dot
        if not '.' in fqdn:
            return Host.objects.none()
        splitted = fqdn.split('.', 1)
        return Host.objects.filter(
            subdomain=splitted[0], domain__domain=splitted[1], **kwargs)

    def getIPv4(self):
        try:
            return dnstools.query_ns(self.get_fqdn(), 'A', origin=self.domain.domain)
        except (dns.resolver.NXDOMAIN, dns.resolver.NoAnswer, dns.resolver.NoNameservers, dns.resolver.Timeout):
            return ''

    def getIPv6(self):
        try:
            return dnstools.query_ns(self.get_fqdn(), 'AAAA', origin=self.domain.domain)
        except (dns.resolver.NXDOMAIN, dns.resolver.NoAnswer, dns.resolver.NoNameservers, dns.resolver.Timeout):
            return ''

    def poke(self):
        self.last_api_update = datetime.now()
        self.save()

    def generate_secret(self):
        # note: we use a quick hasher for the update_secret as expensive
        # more modern hashes might put too much load on the servers. also
        # many update clients might use http without ssl, so it is not too
        # secure anyway.
        secret = User.objects.make_random_password()
        self.update_secret = make_password(
            secret,
            hasher='sha1'
        )
        self.save()
        return secret


def post_delete_host(sender, **kwargs):
    obj = kwargs['instance']
    dnstools.delete(obj.get_fqdn(), origin=obj.domain.domain)


post_delete.connect(post_delete_host, sender=Host)

hopperpw/main/forms.py
# -*- coding: utf-8 -*-
from django import forms
from main.models import Host, Domain


class CreateHostForm(forms.ModelForm):
    class Meta:
        model = Host
        fields = ['subdomain', 'domain', 'comment']


class EditHostForm(forms.ModelForm):
    class Meta:
        model = Host
        fields = ['comment']


class CreateDomainForm(forms.ModelForm):
    class Meta:
        model = Domain
        exclude = ['created_by']

hopperpw/main/views.py
# -*- coding: utf-8 -*-
from django.db.models import Q
from django.views.generic import TemplateView, CreateView
from django.views.generic.edit import UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse
from django.core.exceptions import PermissionDenied
import dns.inet
import dnstools

from main.utils import get_remote_addr
from main.forms import CreateHostForm, EditHostForm, CreateDomainForm
from main.models import Host, Domain


class GenerateSecretView(UpdateView):
    model = Host
    template_name = "main/generate_secret.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(GenerateSecretView, self).dispatch(*args, **kwargs)

    def get_object(self, *args, **kwargs):
        obj = super(GenerateSecretView, self).get_object(*args, **kwargs)
        if obj.created_by != self.request.user:
            raise PermissionDenied()  # or Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super(GenerateSecretView, self).get_context_data(**kwargs)
        context['nav_overview'] = True
        # generate secret, store it hashed and
        # return the plain secret for the context
        context['update_secret'] = self.object.generate_secret()
        context['hosts'] = Host.objects.filter(created_by=self.request.user)
        messages.add_message(self.request, messages.SUCCESS, 'Host secret created.')
        return context


class AboutView(TemplateView):
    template_name = "main/about.html"

    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context['nav_about'] = True
        return context


class ThankYouView(TemplateView):
    template_name = "main/thank_you.html"

    def get_context_data(self, **kwargs):
        context = super(ThankYouView, self).get_context_data(**kwargs)
        context['nav_thank_you'] = True
        return context


class HomeView(TemplateView):
    template_name = "main/home.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['nav_home'] = True

        s = self.request.session
        ipaddr = get_remote_addr(self.request)
        af = dns.inet.af_for_address(ipaddr)
        key = 'ipv4' if af == dns.inet.AF_INET else 'ipv6'
        s[key] = ipaddr
        s.save()

        return context


class HelpView(TemplateView):
    template_name = "main/help.html"

    def get_context_data(self, **kwargs):
        context = super(HelpView, self).get_context_data(**kwargs)
        context['nav_help'] = True
        return context


class RegistrationSuccessView(TemplateView):
    template_name = 'main/registration_success.html'


class OverviewView(CreateView):
    model = Host
    template_name = "main/overview.html"
    form_class = CreateHostForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(OverviewView, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('generate_secret_view', args=(self.object.pk,))

    def get_form(self, form_class):
        form = super(OverviewView, self).get_form(form_class)
        form.fields['domain'].queryset = Domain.objects.filter(
            Q(created_by=self.request.user) | Q(available_for_everyone=True))
        return form

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        dnstools.add(
            self.object.get_fqdn(),
            get_remote_addr(self.request),
            origin=self.object.domain.domain
        )
        messages.add_message(self.request, messages.SUCCESS, 'Host added.')
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(OverviewView, self).get_context_data(**kwargs)
        context['nav_overview'] = True
        context['hosts'] = Host.objects.filter(created_by=self.request.user)
        return context


class HostView(UpdateView):
    model = Host
    template_name = "main/host.html"
    form_class = EditHostForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(HostView, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('overview')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        messages.add_message(self.request, messages.SUCCESS, 'Host updated.')
        return HttpResponseRedirect(self.get_success_url())

    def get_object(self, *args, **kwargs):
        obj = super(HostView, self).get_object(*args, **kwargs)
        if obj.created_by != self.request.user:
            raise PermissionDenied()  # or Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super(HostView, self).get_context_data(**kwargs)
        context['nav_overview'] = True
        context['remote_addr'] = get_remote_addr(self.request)
        context['hosts'] = Host.objects.filter(created_by=self.request.user)
        return context


class DeleteHostView(DeleteView):
    model = Host
    template_name = "main/delete_object.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DeleteHostView, self).dispatch(*args, **kwargs)

    def get_object(self, *args, **kwargs):
        obj = super(DeleteHostView, self).get_object(*args, **kwargs)
        if obj.created_by != self.request.user:
            raise PermissionDenied()  # or Http404
        return obj

    def get_success_url(self):
        return reverse('overview')


class DomainOverwievView(CreateView):
    model = Domain
    template_name = "main/domain_overview.html"
    form_class = CreateDomainForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DomainOverwievView, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('domain_overview')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        messages.add_message(self.request, messages.SUCCESS, 'Domain added.')
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(
            DomainOverwievView, self).get_context_data(**kwargs)
        context['nav_domains'] = True
        context['domains'] = Domain.objects.filter(
            created_by=self.request.user)
        return context


class DeleteDomainView(DeleteView):
    model = Domain
    template_name = "main/delete_object.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DeleteDomainView, self).dispatch(*args, **kwargs)

    def get_object(self, *args, **kwargs):
        obj = super(DeleteDomainView, self).get_object(*args, **kwargs)
        if obj.created_by != self.request.user:
            raise PermissionDenied()  # or Http404
        return obj

    def get_success_url(self):
        return reverse('domain_overview')

hopperpw/main/templates/main/about.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class="row">
    <div class="col-xs-12">
        <h1 class="text-center">About hopper.pw</h1>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-5">
        <h3>What's this?</h3>
        <p>
        hopper.pw is a free dynamic DNS service, as well as an
        <a href="https://github.com/asmaps/hopper.pw"><i class="fa fa-github-square"></i>open source software project</a>.
        </p>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-7 col-sm-offset-3">
        <h3>What the heck is (dynamic) DNS!?</h3>
        <p>
        DNS stands for Domain Name System. This is the "addressbook" of the internet:
        Every device in the internet has an IP address - but because people are bad at
        remembering numbers DNS translates easy to remember names to IP addresses.<br>
        Your router at home also is a device in the internet, so it has an IP address -
        but oh... it does NOT automatically have a DNS entry. Also your IP address
        changes regularly. To update a DNS entry most routers have the option to report
        their IP address to a dynamic DNS service (like hopper.pw) if it changed.
        So you can reach your home router from the internet at anytime (e.g. for remote
        administration or switching off the lights)
        </p>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-1">
        <h3>Where do I get a domain (DNS entry) from?</h3>
        <p>
        As part of the free service hopper.pw offers a subdomain (&lt;something&gt;.hopper.pw) for you.
        If you are more advanced, have your own domain and a nsupdate-capable
        DNS server you can add your own domain.
        </p>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-5 col-sm-offset-7 col-md-3 col-md-offset-9">
        <h3>What does it cost?</h3>
        <p>
        Nothing! The service is completely free of charge. No hidden costs!
        </p>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-2">
        <h3>How is hopper.pw funded?</h3>
        <p>
        hopper.pw is completely funded from private pocket. If you want to support
        hopper.pw, keep the service running and help me pay for the server
        please consider donating or pressing the flattr button.
        If you don't want to support with money just <strong>spread the word</strong>
        or make your own contributions to the project.
        </p>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-7 col-sm-offset-5">
        <h3>Why another dyndns service?</h3>
        <p>
        Yes - there are already various other dyndns services. Buuuuut...
        We were annoyed by always having to click on a link in an email every couple of days
        to prevent the deletion of the domain on other widely spread services and also to always
        try finding the well hidden button for the free accounts. That's why we thought
        "let's host our own service - can't be to difficult!". So during djangodash 2013
        nsupdate.info was born. After the dash the project split into two forks: nsupdate.info
        and hopper.pw.
        </p>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-4">
        <h3>Who is maintaining hopper.pw?</h3>
        <p>
        Hopper.pw is maintained and funded by <a href="https://github.com/asmaps/">Arne Schauf</a>. The first version was developed on djangodash 2013.
        </p>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-5 col-sm-offset-7">
        <h3>Is it reliable?</h3>
        <p>
        I try to do my best to keep the service up and running.<br>
        But: This is a free service, there are no warranties. If it breaks, it breaks.
        </p>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 text-center">
        <h3>Any questions left?</h3>
        <p>
        Please do not hesitate to contact me: contact_about@hopper.pw
        </p>
    </div>
</div>
{% endblock %}

hopperpw/main/templates/main/delete_object.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
    <div class="row">
         <div class="col-lg-8">
            <h3>Delete {{ object }}</h3>
            <form action="" method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                <button type="submit" class="btn btn-primary">Confirm</button>
            </form>
        </div>
    </div>
{% endblock %}

hopperpw/main/templates/main/domain_overview.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h3>My domains</h3>
            <table class="table">
            <thead><th>Domain</th><th>Nameserver IP</th><th>Update key</th><th>Algorithm</th><th>Public?</th><th>Action</th></thead>
            {% for domain in domains %}
                <tr>
                    <td><b>{{ domain.domain }}</b></td>
                    <td>{{ domain.nameserver_ip }}</td>
                    <td>{{ domain.nameserver_update_key }}</td>
                    <td>{{ domain.get_nameserver_update_algorithm_display }}</td>
                    <td>{{ domain.available_for_everyone|yesno }}</td>
                    <td>
                        <a href="{% url 'delete_domain' domain.pk %}"><i class="icon icon-remove"></i> delete</a>
                    </td>
                </tr>
            {% empty %}
                <tr><td colspan="6">No domains yet.</td></tr>
            {% endfor %}
            </table>
        </div>
    </div>
    <hr>

    <div class="row">
        <div class="col-lg-4">
            <div class="well well-sm">
                <h3>New Domain</h3>
                <h4><em>Feature temporarilly disabled</em></h4>
                {% comment %}
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form|bootstrap }}
                    <button type="submit" class="btn btn-primary">Create</button>
                </form>
                {% endcomment %}
            </div>
        </div>
        <div class="col-lg-8">
            <div class="well well-sm">
                <h3>Information</h3>
                <p>Informational text goes here</p>
            </div>
        </div>
    </div>
{% endblock %}

hopperpw/main/templates/main/generate_secret.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class="row">
    <div class="col-lg-4">
        <div class="well">
            <h3>Host Secret Generated <small><br>
            <a href="{% url 'overview' %}"><i class="icon-double-angle-left"></i> back to overview</a></small></h3>
            <p>New secret generated for you. We store it hashed, so save it now, or you have to generate a new one again. Everytime you visit this page a new secret will be generated and the old one becomes invalid.</p>
            <p>Secret: <b>{{ update_secret }}</b></p>
        </div>
    </div>
    <div class="col-lg-8">
        <div class="well">
            <h3>How to configure your router?</h3>
            {% include "main/includes/tabbed_router_configuration.html" with host=object %}
        </div>
    </div>
</div>
{% endblock %}

hopperpw/main/templates/main/help.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<h1>Help / FAQ</h1>
<div class="row">
    <div class="col-lg-5">
        <div class="well">
            <h2>Stuck?</h2>
            Join #hopper.pw on freenode (IRC):
            <div style="margin:20px">
                <strong>chat.freenode.net</strong><br>
                <strong>#hopper.pw</strong><br>
            </div>
            Maybe somebody can help you.
        </div>
        <div class="well">
            <h2>Standards used?</h2>
            We use:
            <ul>
                <li>Frontend Update-API: dyndns2 protocol
                    <ul>
                        <li><a href="http://dyn.com/support/developers/api/">dyndns2 api description on dyn.com</a></li>
                        <li><a href="http://www.noip.com/integrate/">dyndns2 api description on noip.com</a></li>
                    </ul>
                </li>
                <li>Backend: dynamic DNS update (see <a href="http://www.ietf.org/rfc/rfc2136.txt">RFC2136</a>)</li>
            </ul>
        </div>
    </div>
    <div class="col-lg-7">
        <div class="well">
            <h3>How to configure your router?</h3>
            {% include "main/includes/tabbed_router_configuration.html" with host=object %}
        </div>
    </div>
</div>
{% endblock %}

hopperpw/main/templates/main/home.html
{% extends "base.html" %}
{% load bootstrap %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'magnific-popup/magnific-popup.css' %}">
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-10 col-xs-12">
        <div class="jumbotron">
            {% if request.session.ipv4 %}
            <h1 style="margin-bottom:0px">{{request.session.ipv4}} <small>IPv4</small></h1>
            {% endif %}
            {% if request.session.ipv6 %}
            <h2 style="margin-top:0px;margin-bottom:30px">{{request.session.ipv6}} <small>IPv6</small></h2>
            {% endif %}
            <h3 class="indent">Free and open source dynamic DNS<br>
                <small>No annoying mails, simple interface - easy to use!</small></h3>
            <div class="mtop10 mbot10">
                {% include "social_widgets.html" %}
                {% if not request.user.is_authenticated %}
                <div class="pull-right">
                    <a href="{% url 'account_signup' %}" class="btn btn-success btn-lg"><i class="fa fa-star-o"></i> Sign up for free</a>
                </div>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4" style="text-align: center">
                <h1><i class="fa fa-globe fa-3x"></i></h1>
                <h3>World Wide Web</h3>
                <p>
                Reach your home whenever you want!
                </p>
            </div>
            <div class="col-sm-4" style="text-align: center">
                <h1><i class="fa fa-github fa-3x"></i></h1>
                <h3>Open Source and free</h3>
                <p>
                hopper.pw is a free to use, open source dynamic DNS service with IPv4 and IPv6 support.
                </p>
            </div>
            <div class="col-sm-4" style="text-align: center">
                <h1><i class="fa fa-rocket fa-3x"></i></h1>
                <h3>Rocket science</h3>
                <p>
                hopper.pw relies on an awesome software stack:<br>
                <a target="_blank" href="http://www.python.org">python</a>,
                <a target="_blank" href="http://www.djangoproject.com">django</a>,
                <a target="_blank" href="http://www.postgres.org">postgres</a>,
                <a target="_blank" href="http://www.nginx.org">nginx</a> and
                <a target="_blank" href="http://www.powerdns.com">powerdns</a>
                </p>
            </div>
        </div>
    </div>
    {% if ENABLE_ADS %}
    <div class="col-lg-2 ad-160-600 text-center visible-lg">
        {% include "ads/ad_wide_skyscraper.html" %}
    </div>
    <div class="col-md-2 ad-120-600 text-center visible-md">
        {% include "ads/ad_skyscraper.html" %}
    </div>
    {% endif %}
</div>
<hr>
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <h3>Screenshots</h3>
        <div id="screenshot-carousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#screenshot-carousel" data-slide-to="0" class="active"></li>
                <li data-target="#screenshot-carousel" data-slide-to="1"></li>
                <li data-target="#screenshot-carousel" data-slide-to="2"></li>
                <li data-target="#screenshot-carousel" data-slide-to="3"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <a href="{% static 'screenshots/overview.png' %}" class="mfp-image">
                        <img src="{% static 'screenshots/overview.png' %}">
                    </a>
                </div>
                <div class="item">
                    <a href="{% static 'screenshots/stats.png' %}" class="mfp-image">
                        <img src="{% static 'screenshots/stats.png' %}">
                    </a>
                </div>
                <div class="item">
                    <a href="{% static 'screenshots/generatesecret.png' %}" class="mfp-image">
                        <img src="{% static 'screenshots/generatesecret.png' %}">
                    </a>
                </div>
                <div class="item">
                    <a href="{% static 'screenshots/hostview.png' %}" class="mfp-image">
                        <img src="{% static 'screenshots/hostview.png' %}">
                    </a>
                </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#screenshot-carousel" data-slide="prev">
                <span class="fa fa-angle-left icon-prev"></span>
            </a>
            <a class="right carousel-control" href="#screenshot-carousel" data-slide="next">
                <span class="fa fa-angle-right icon-next"></span>
            </a>
        </div>
    </div>
</div>
<hr>
{% if ENABLE_ADS %}
<div class="row ad-728-90 hidden-xs">
    <div class="text-center col-lg-12">
        {% include "ads/ad_leaderboard.html" %}
    </div>
</div>
<div class="row ad-336-280 visible-xs">
    <div class="text-center col-lg-12">
        {% include "ads/ad_large_rectangle.html" %}
    </div>
</div>
{% endif %}

{% endblock %}

{% block bottom_js %}
<script src="{% static 'magnific-popup/jquery.magnific-popup.min.js' %}"></script>
<script>
$(document).ready(function() {

        $('.mfp-image').magnificPopup({
type:'image',
removalDelay: 300,
mainClass: 'mfp-fade'
});

        });
</script>
{% endblock bottom_js %}

hopperpw/main/templates/main/thank_you.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class="text-center">
    <h1>Thank you for your support!</h1>
    <p>Thank you very much for your support. This will help keeping hopper.pw online!</p>
    <a href="{% url 'home' %}" class="btn btn-lg btn-success">Bring me back to the main page</a>
</div>
{% endblock %}